//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanThuoc.QLBanThuoc_RF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QLBanThuoc_RF.QLBanThuocServiceSoap")]
    public interface QLBanThuocServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        QLBanThuoc.QLBanThuoc_RF.HelloWorldResponse HelloWorld(QLBanThuoc.QLBanThuoc_RF.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QLBanThuoc_RF.HelloWorldResponse> HelloWorldAsync(QLBanThuoc.QLBanThuoc_RF.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public QLBanThuoc.QLBanThuoc_RF.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(QLBanThuoc.QLBanThuoc_RF.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public QLBanThuoc.QLBanThuoc_RF.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(QLBanThuoc.QLBanThuoc_RF.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QLBanThuocServiceSoapChannel : QLBanThuoc.QLBanThuoc_RF.QLBanThuocServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QLBanThuocServiceSoapClient : System.ServiceModel.ClientBase<QLBanThuoc.QLBanThuoc_RF.QLBanThuocServiceSoap>, QLBanThuoc.QLBanThuoc_RF.QLBanThuocServiceSoap {
        
        public QLBanThuocServiceSoapClient() {
        }
        
        public QLBanThuocServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QLBanThuocServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLBanThuocServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLBanThuocServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLBanThuoc.QLBanThuoc_RF.HelloWorldResponse QLBanThuoc.QLBanThuoc_RF.QLBanThuocServiceSoap.HelloWorld(QLBanThuoc.QLBanThuoc_RF.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            QLBanThuoc.QLBanThuoc_RF.HelloWorldRequest inValue = new QLBanThuoc.QLBanThuoc_RF.HelloWorldRequest();
            inValue.Body = new QLBanThuoc.QLBanThuoc_RF.HelloWorldRequestBody();
            QLBanThuoc.QLBanThuoc_RF.HelloWorldResponse retVal = ((QLBanThuoc.QLBanThuoc_RF.QLBanThuocServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QLBanThuoc.QLBanThuoc_RF.HelloWorldResponse> QLBanThuoc.QLBanThuoc_RF.QLBanThuocServiceSoap.HelloWorldAsync(QLBanThuoc.QLBanThuoc_RF.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QLBanThuoc_RF.HelloWorldResponse> HelloWorldAsync() {
            QLBanThuoc.QLBanThuoc_RF.HelloWorldRequest inValue = new QLBanThuoc.QLBanThuoc_RF.HelloWorldRequest();
            inValue.Body = new QLBanThuoc.QLBanThuoc_RF.HelloWorldRequestBody();
            return ((QLBanThuoc.QLBanThuoc_RF.QLBanThuocServiceSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
