//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanThuoc.QL_SR {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QL_SR.QLBanThuocServiceSoap")]
    public interface QLBanThuocServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemMoiNCC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ThemMoiNCC(string mancc, string tenncc, string nguoidd, string sdt, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemMoiNCC", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ThemMoiNCCAsync(string mancc, string tenncc, string nguoidd, string sdt, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuaNhaCungCap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SuaNhaCungCap(string mancc, string tenncc, string nguoidd, string sdt, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuaNhaCungCap", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SuaNhaCungCapAsync(string mancc, string tenncc, string nguoidd, string sdt, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaNhaCungCap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int XoaNhaCungCap(string mancc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaNhaCungCap", ReplyAction="*")]
        System.Threading.Tasks.Task<int> XoaNhaCungCapAsync(string mancc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemNCC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiemNCC(string thongtin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemNCC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TimKiemNCCAsync(string thongtin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getID(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getIDAsync(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ma_user", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ma_user();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ma_user", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ma_userAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiemThuoc(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuocAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuocSua", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiemThuocSua(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuocSua", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuocSuaAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LuuThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int LuuThuoc(string mathuoc, string malo, string ten, string tp, string cd, string nsx, string hsd, string slt, string dt, string dongia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LuuThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<int> LuuThuocAsync(string mathuoc, string malo, string ten, string tp, string cd, string nsx, string hsd, string slt, string dt, string dongia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int XoaThuoc(string maThuoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<int> XoaThuocAsync(string maThuoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DanhSachThuoc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DanhSachThuocAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThuocTheoTen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DanhSachThuocTheoTen(string TenThuoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThuocTheoTen", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DanhSachThuocTheoTenAsync(string TenThuoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThuocTheoThoiHan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DanhSachThuocTheoThoiHan(string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThuocTheoThoiHan", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DanhSachThuocTheoThoiHanAsync(string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThuocTheoTenVaThoiHan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DanhSachThuocTheoTenVaThoiHan(string TenThuoc, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThuocTheoTenVaThoiHan", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DanhSachThuocTheoTenVaThoiHanAsync(string TenThuoc, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DangKy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DangKy(string tenDangNhap, string MatKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DangKy", ReplyAction="*")]
        System.Threading.Tasks.Task DangKyAsync(string tenDangNhap, string MatKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoiMatKhau", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DoiMatKhau(string tenDangNhap, string MatKhauCu, string MatKhauMoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoiMatKhau", ReplyAction="*")]
        System.Threading.Tasks.Task DoiMatKhauAsync(string tenDangNhap, string MatKhauCu, string MatKhauMoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NhapThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int NhapThuoc(string maThuoc, string maHSX, string NSX, string HSD, string tenThuoc, string CD, string TP, string SL, string maDang, string maLoai, string date, string maNCC, string maNV, string Gia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NhapThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<int> NhapThuocAsync(string maThuoc, string maHSX, string NSX, string HSD, string tenThuoc, string CD, string TP, string SL, string maDang, string maLoai, string date, string maNCC, string maNV, string Gia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimNCC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimNCC(string TenNCC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimNCC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TimNCCAsync(string TenNCC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadThongTinNV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LoadThongTinNV(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadThongTinNV", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LoadThongTinNVAsync(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadThongTinHSX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LoadThongTinHSX(string tenHSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadThongTinHSX", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LoadThongTinHSXAsync(string tenHSX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadThongTinLoaiThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LoadThongTinLoaiThuoc(string tenLoaiThuoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadThongTinLoaiThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LoadThongTinLoaiThuocAsync(string tenLoaiThuoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getRole(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRole", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getRoleAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thongke_ThuocNhap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Thongke_ThuocNhap(string str1, string str2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thongke_ThuocNhap", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Thongke_ThuocNhapAsync(string str1, string str2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thongke_ThuocBan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Thongke_ThuocBan(string str1, string str2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thongke_ThuocBan", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Thongke_ThuocBanAsync(string str1, string str2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThongkeSLT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ThongkeSLT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThongkeSLT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ThongkeSLTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThongkeTHH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ThongkeTHH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThongkeTHH", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ThongkeTHHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TKDoanhThuMY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TKDoanhThuMY(string date1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TKDoanhThuMY", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TKDoanhThuMYAsync(string date1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TKDoanhThuY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TKDoanhThuY(string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TKDoanhThuY", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TKDoanhThuYAsync(string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TKDoanhThu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TKDoanhThu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TKDoanhThu", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TKDoanhThuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemKH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiemKH(string cmnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemKH", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TimKiemKHAsync(string cmnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemKH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ThemKH(string ten, string SDT, string cmtnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemKH", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ThemKHAsync(string ten, string SDT, string cmtnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuoc_Ban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiemThuoc_Ban(string cmnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuoc_Ban", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuoc_BanAsync(string cmnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemPhieuXuat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ThemPhieuXuat(string date, string makh, string manv, string tong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemPhieuXuat", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ThemPhieuXuatAsync(string date, string makh, string manv, string tong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemPhieuXuat1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ThemPhieuXuat1(string date, string makh, string manv, string tong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemPhieuXuat1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ThemPhieuXuat1Async(string date, string makh, string manv, string tong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayMaPX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LayMaPX(string date, string makh, string manv, string tong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayMaPX", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LayMaPXAsync(string date, string makh, string manv, string tong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemDonThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ThemDonThuoc(string maPX, string maT, string sl, string gia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemDonThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ThemDonThuocAsync(string maPX, string maT, string sl, string gia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayThuocDatHang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LayThuocDatHang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayThuocDatHang", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LayThuocDatHangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayThuocDaDatHang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LayThuocDaDatHang(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayThuocDaDatHang", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LayThuocDaDatHangAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayThuocDatHangChiTiet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LayThuocDatHangChiTiet(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayThuocDatHangChiTiet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LayThuocDatHangChiTietAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayThuocDonThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LayThuocDonThuoc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayThuocDonThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LayThuocDonThuocAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuocDonThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiemThuocDonThuoc(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuocDonThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuocDonThuocAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemChiTietDonThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiemChiTietDonThuoc(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemChiTietDonThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TimKiemChiTietDonThuocAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaDon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void XoaDon(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaDon", ReplyAction="*")]
        System.Threading.Tasks.Task XoaDonAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.THUOC[] LayDS(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayDS", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> LayDSAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.KHACHHANG[] Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.KHACHHANG[]> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiem_W", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.THUOC[] TimKiem_W(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiem_W", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> TimKiem_WAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Register(string email, string password, string name, string makh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RegisterAsync(string email, string password, string name, string makh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayTenLoaiThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.THUOC[] LayTenLoaiThuoc(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayTenLoaiThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> LayTenLoaiThuocAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChiTietSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.THUOC[] ChiTietSP(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChiTietSP", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> ChiTietSPAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayDSLoaiThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.LOAITHUOC[] LayDSLoaiThuoc(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayDSLoaiThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.LOAITHUOC[]> LayDSLoaiThuocAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThongTinKH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.KHACHHANG[] ThongTinKH(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThongTinKH", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.KHACHHANG[]> ThongTinKHAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThongTinGH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.GIOHANG[] ThongTinGH(string maKH, string maT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThongTinGH", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.GIOHANG[]> ThongTinGHAsync(string maKH, string maT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TienKM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.KHUYENMAI[] TienKM(string coupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TienKM", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.KHUYENMAI[]> TienKMAsync(string coupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ThemSP(string maT, string maKH, int sl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemSP", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ThemSPAsync(string maT, string maKH, int sl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int XoaSP(string maKH, string maT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaSP", ReplyAction="*")]
        System.Threading.Tasks.Task<int> XoaSPAsync(string maKH, string maT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemHoaDon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ThemHoaDon(string ho, string ten, string diachiduong, string sonha, string email, string sdt, string ghichu, string makhuyenmai, string giaohang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemHoaDon", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ThemHoaDonAsync(string ho, string ten, string diachiduong, string sonha, string email, string sdt, string ghichu, string makhuyenmai, string giaohang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayMaHD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.HOADON[] LayMaHD(string ho, string ten, string diachiduong, string sonha, string email, string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayMaHD", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.HOADON[]> LayMaHDAsync(string ho, string ten, string diachiduong, string sonha, string email, string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemCCHoaDon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ThemCCHoaDon(int maHD, string maT, int dongia, int sl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemCCHoaDon", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ThemCCHoaDonAsync(int maHD, string maT, int dongia, int sl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SanPhamBanChay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.THUOC[] SanPhamBanChay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SanPhamBanChay", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> SanPhamBanChayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SanPhamMoi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLBanThuoc.QL_SR.THUOC[] SanPhamMoi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SanPhamMoi", ReplyAction="*")]
        System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> SanPhamMoiAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class THUOC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maThuocField;
        
        private string tenThuocField;
        
        private string congDungField;
        
        private string thanhPhanField;
        
        private int soLuongTonField;
        
        private string dangThuocField;
        
        private string maLoaiThuocField;
        
        private int donGiaField;
        
        private string maHangSXField;
        
        private string maNhaCungCapField;
        
        private string urlImageField;
        
        private string tienField;
        
        private string timKiemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaThuoc {
            get {
                return this.maThuocField;
            }
            set {
                this.maThuocField = value;
                this.RaisePropertyChanged("MaThuoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TenThuoc {
            get {
                return this.tenThuocField;
            }
            set {
                this.tenThuocField = value;
                this.RaisePropertyChanged("TenThuoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CongDung {
            get {
                return this.congDungField;
            }
            set {
                this.congDungField = value;
                this.RaisePropertyChanged("CongDung");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ThanhPhan {
            get {
                return this.thanhPhanField;
            }
            set {
                this.thanhPhanField = value;
                this.RaisePropertyChanged("ThanhPhan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SoLuongTon {
            get {
                return this.soLuongTonField;
            }
            set {
                this.soLuongTonField = value;
                this.RaisePropertyChanged("SoLuongTon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DangThuoc {
            get {
                return this.dangThuocField;
            }
            set {
                this.dangThuocField = value;
                this.RaisePropertyChanged("DangThuoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MaLoaiThuoc {
            get {
                return this.maLoaiThuocField;
            }
            set {
                this.maLoaiThuocField = value;
                this.RaisePropertyChanged("MaLoaiThuoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int DonGia {
            get {
                return this.donGiaField;
            }
            set {
                this.donGiaField = value;
                this.RaisePropertyChanged("DonGia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MaHangSX {
            get {
                return this.maHangSXField;
            }
            set {
                this.maHangSXField = value;
                this.RaisePropertyChanged("MaHangSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MaNhaCungCap {
            get {
                return this.maNhaCungCapField;
            }
            set {
                this.maNhaCungCapField = value;
                this.RaisePropertyChanged("MaNhaCungCap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UrlImage {
            get {
                return this.urlImageField;
            }
            set {
                this.urlImageField = value;
                this.RaisePropertyChanged("UrlImage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Tien {
            get {
                return this.tienField;
            }
            set {
                this.tienField = value;
                this.RaisePropertyChanged("Tien");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TimKiem {
            get {
                return this.timKiemField;
            }
            set {
                this.timKiemField = value;
                this.RaisePropertyChanged("TimKiem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HOADON : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int maHoaDonField;
        
        private string tenKhachHangField;
        
        private string diaChiField;
        
        private string soDienThoaiField;
        
        private string emailField;
        
        private string ghiChuField;
        
        private string maKhuyenMaiField;
        
        private string hinhThucGiaoHangField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MaHoaDon {
            get {
                return this.maHoaDonField;
            }
            set {
                this.maHoaDonField = value;
                this.RaisePropertyChanged("MaHoaDon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TenKhachHang {
            get {
                return this.tenKhachHangField;
            }
            set {
                this.tenKhachHangField = value;
                this.RaisePropertyChanged("TenKhachHang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
                this.RaisePropertyChanged("DiaChi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SoDienThoai {
            get {
                return this.soDienThoaiField;
            }
            set {
                this.soDienThoaiField = value;
                this.RaisePropertyChanged("SoDienThoai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string GhiChu {
            get {
                return this.ghiChuField;
            }
            set {
                this.ghiChuField = value;
                this.RaisePropertyChanged("GhiChu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MaKhuyenMai {
            get {
                return this.maKhuyenMaiField;
            }
            set {
                this.maKhuyenMaiField = value;
                this.RaisePropertyChanged("MaKhuyenMai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string HinhThucGiaoHang {
            get {
                return this.hinhThucGiaoHangField;
            }
            set {
                this.hinhThucGiaoHangField = value;
                this.RaisePropertyChanged("HinhThucGiaoHang");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KHUYENMAI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maKMField;
        
        private int tienKMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaKM {
            get {
                return this.maKMField;
            }
            set {
                this.maKMField = value;
                this.RaisePropertyChanged("MaKM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TienKM {
            get {
                return this.tienKMField;
            }
            set {
                this.tienKMField = value;
                this.RaisePropertyChanged("TienKM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GIOHANG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int maGHField;
        
        private string maThuocField;
        
        private string maKhachHangField;
        
        private int soLuongField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MaGH {
            get {
                return this.maGHField;
            }
            set {
                this.maGHField = value;
                this.RaisePropertyChanged("MaGH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MaThuoc {
            get {
                return this.maThuocField;
            }
            set {
                this.maThuocField = value;
                this.RaisePropertyChanged("MaThuoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MaKhachHang {
            get {
                return this.maKhachHangField;
            }
            set {
                this.maKhachHangField = value;
                this.RaisePropertyChanged("MaKhachHang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SoLuong {
            get {
                return this.soLuongField;
            }
            set {
                this.soLuongField = value;
                this.RaisePropertyChanged("SoLuong");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LOAITHUOC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maLoaiThuocField;
        
        private string tenLoaiThuocField;
        
        private string parentIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaLoaiThuoc {
            get {
                return this.maLoaiThuocField;
            }
            set {
                this.maLoaiThuocField = value;
                this.RaisePropertyChanged("MaLoaiThuoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TenLoaiThuoc {
            get {
                return this.tenLoaiThuocField;
            }
            set {
                this.tenLoaiThuocField = value;
                this.RaisePropertyChanged("TenLoaiThuoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
                this.RaisePropertyChanged("ParentID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KHACHHANG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maKhachHangField;
        
        private string tenKhachHangField;
        
        private string emailField;
        
        private string matKhauField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaKhachHang {
            get {
                return this.maKhachHangField;
            }
            set {
                this.maKhachHangField = value;
                this.RaisePropertyChanged("MaKhachHang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TenKhachHang {
            get {
                return this.tenKhachHangField;
            }
            set {
                this.tenKhachHangField = value;
                this.RaisePropertyChanged("TenKhachHang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MatKhau {
            get {
                return this.matKhauField;
            }
            set {
                this.matKhauField = value;
                this.RaisePropertyChanged("MatKhau");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QLBanThuocServiceSoapChannel : QLBanThuoc.QL_SR.QLBanThuocServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QLBanThuocServiceSoapClient : System.ServiceModel.ClientBase<QLBanThuoc.QL_SR.QLBanThuocServiceSoap>, QLBanThuoc.QL_SR.QLBanThuocServiceSoap {
        
        public QLBanThuocServiceSoapClient() {
        }
        
        public QLBanThuocServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QLBanThuocServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLBanThuocServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLBanThuocServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ThemMoiNCC(string mancc, string tenncc, string nguoidd, string sdt, string diachi) {
            return base.Channel.ThemMoiNCC(mancc, tenncc, nguoidd, sdt, diachi);
        }
        
        public System.Threading.Tasks.Task<int> ThemMoiNCCAsync(string mancc, string tenncc, string nguoidd, string sdt, string diachi) {
            return base.Channel.ThemMoiNCCAsync(mancc, tenncc, nguoidd, sdt, diachi);
        }
        
        public int SuaNhaCungCap(string mancc, string tenncc, string nguoidd, string sdt, string diachi) {
            return base.Channel.SuaNhaCungCap(mancc, tenncc, nguoidd, sdt, diachi);
        }
        
        public System.Threading.Tasks.Task<int> SuaNhaCungCapAsync(string mancc, string tenncc, string nguoidd, string sdt, string diachi) {
            return base.Channel.SuaNhaCungCapAsync(mancc, tenncc, nguoidd, sdt, diachi);
        }
        
        public int XoaNhaCungCap(string mancc) {
            return base.Channel.XoaNhaCungCap(mancc);
        }
        
        public System.Threading.Tasks.Task<int> XoaNhaCungCapAsync(string mancc) {
            return base.Channel.XoaNhaCungCapAsync(mancc);
        }
        
        public System.Data.DataTable TimKiemNCC(string thongtin) {
            return base.Channel.TimKiemNCC(thongtin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TimKiemNCCAsync(string thongtin) {
            return base.Channel.TimKiemNCCAsync(thongtin);
        }
        
        public string getID(string username, string pass) {
            return base.Channel.getID(username, pass);
        }
        
        public System.Threading.Tasks.Task<string> getIDAsync(string username, string pass) {
            return base.Channel.getIDAsync(username, pass);
        }
        
        public string ma_user() {
            return base.Channel.ma_user();
        }
        
        public System.Threading.Tasks.Task<string> ma_userAsync() {
            return base.Channel.ma_userAsync();
        }
        
        public System.Data.DataTable TimKiemThuoc(string str) {
            return base.Channel.TimKiemThuoc(str);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuocAsync(string str) {
            return base.Channel.TimKiemThuocAsync(str);
        }
        
        public System.Data.DataTable TimKiemThuocSua(string str) {
            return base.Channel.TimKiemThuocSua(str);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuocSuaAsync(string str) {
            return base.Channel.TimKiemThuocSuaAsync(str);
        }
        
        public int LuuThuoc(string mathuoc, string malo, string ten, string tp, string cd, string nsx, string hsd, string slt, string dt, string dongia) {
            return base.Channel.LuuThuoc(mathuoc, malo, ten, tp, cd, nsx, hsd, slt, dt, dongia);
        }
        
        public System.Threading.Tasks.Task<int> LuuThuocAsync(string mathuoc, string malo, string ten, string tp, string cd, string nsx, string hsd, string slt, string dt, string dongia) {
            return base.Channel.LuuThuocAsync(mathuoc, malo, ten, tp, cd, nsx, hsd, slt, dt, dongia);
        }
        
        public int XoaThuoc(string maThuoc) {
            return base.Channel.XoaThuoc(maThuoc);
        }
        
        public System.Threading.Tasks.Task<int> XoaThuocAsync(string maThuoc) {
            return base.Channel.XoaThuocAsync(maThuoc);
        }
        
        public System.Data.DataTable DanhSachThuoc() {
            return base.Channel.DanhSachThuoc();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DanhSachThuocAsync() {
            return base.Channel.DanhSachThuocAsync();
        }
        
        public System.Data.DataTable DanhSachThuocTheoTen(string TenThuoc) {
            return base.Channel.DanhSachThuocTheoTen(TenThuoc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DanhSachThuocTheoTenAsync(string TenThuoc) {
            return base.Channel.DanhSachThuocTheoTenAsync(TenThuoc);
        }
        
        public System.Data.DataTable DanhSachThuocTheoThoiHan(string date1, string date2) {
            return base.Channel.DanhSachThuocTheoThoiHan(date1, date2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DanhSachThuocTheoThoiHanAsync(string date1, string date2) {
            return base.Channel.DanhSachThuocTheoThoiHanAsync(date1, date2);
        }
        
        public System.Data.DataTable DanhSachThuocTheoTenVaThoiHan(string TenThuoc, string date1, string date2) {
            return base.Channel.DanhSachThuocTheoTenVaThoiHan(TenThuoc, date1, date2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DanhSachThuocTheoTenVaThoiHanAsync(string TenThuoc, string date1, string date2) {
            return base.Channel.DanhSachThuocTheoTenVaThoiHanAsync(TenThuoc, date1, date2);
        }
        
        public void DangKy(string tenDangNhap, string MatKhau) {
            base.Channel.DangKy(tenDangNhap, MatKhau);
        }
        
        public System.Threading.Tasks.Task DangKyAsync(string tenDangNhap, string MatKhau) {
            return base.Channel.DangKyAsync(tenDangNhap, MatKhau);
        }
        
        public void DoiMatKhau(string tenDangNhap, string MatKhauCu, string MatKhauMoi) {
            base.Channel.DoiMatKhau(tenDangNhap, MatKhauCu, MatKhauMoi);
        }
        
        public System.Threading.Tasks.Task DoiMatKhauAsync(string tenDangNhap, string MatKhauCu, string MatKhauMoi) {
            return base.Channel.DoiMatKhauAsync(tenDangNhap, MatKhauCu, MatKhauMoi);
        }
        
        public int NhapThuoc(string maThuoc, string maHSX, string NSX, string HSD, string tenThuoc, string CD, string TP, string SL, string maDang, string maLoai, string date, string maNCC, string maNV, string Gia) {
            return base.Channel.NhapThuoc(maThuoc, maHSX, NSX, HSD, tenThuoc, CD, TP, SL, maDang, maLoai, date, maNCC, maNV, Gia);
        }
        
        public System.Threading.Tasks.Task<int> NhapThuocAsync(string maThuoc, string maHSX, string NSX, string HSD, string tenThuoc, string CD, string TP, string SL, string maDang, string maLoai, string date, string maNCC, string maNV, string Gia) {
            return base.Channel.NhapThuocAsync(maThuoc, maHSX, NSX, HSD, tenThuoc, CD, TP, SL, maDang, maLoai, date, maNCC, maNV, Gia);
        }
        
        public System.Data.DataTable TimNCC(string TenNCC) {
            return base.Channel.TimNCC(TenNCC);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TimNCCAsync(string TenNCC) {
            return base.Channel.TimNCCAsync(TenNCC);
        }
        
        public System.Data.DataTable LoadThongTinNV(string maNV) {
            return base.Channel.LoadThongTinNV(maNV);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LoadThongTinNVAsync(string maNV) {
            return base.Channel.LoadThongTinNVAsync(maNV);
        }
        
        public System.Data.DataTable LoadThongTinHSX(string tenHSX) {
            return base.Channel.LoadThongTinHSX(tenHSX);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LoadThongTinHSXAsync(string tenHSX) {
            return base.Channel.LoadThongTinHSXAsync(tenHSX);
        }
        
        public System.Data.DataTable LoadThongTinLoaiThuoc(string tenLoaiThuoc) {
            return base.Channel.LoadThongTinLoaiThuoc(tenLoaiThuoc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LoadThongTinLoaiThuocAsync(string tenLoaiThuoc) {
            return base.Channel.LoadThongTinLoaiThuocAsync(tenLoaiThuoc);
        }
        
        public System.Data.DataTable getRole(string username) {
            return base.Channel.getRole(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getRoleAsync(string username) {
            return base.Channel.getRoleAsync(username);
        }
        
        public System.Data.DataTable Thongke_ThuocNhap(string str1, string str2) {
            return base.Channel.Thongke_ThuocNhap(str1, str2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Thongke_ThuocNhapAsync(string str1, string str2) {
            return base.Channel.Thongke_ThuocNhapAsync(str1, str2);
        }
        
        public System.Data.DataTable Thongke_ThuocBan(string str1, string str2) {
            return base.Channel.Thongke_ThuocBan(str1, str2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Thongke_ThuocBanAsync(string str1, string str2) {
            return base.Channel.Thongke_ThuocBanAsync(str1, str2);
        }
        
        public System.Data.DataTable ThongkeSLT() {
            return base.Channel.ThongkeSLT();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ThongkeSLTAsync() {
            return base.Channel.ThongkeSLTAsync();
        }
        
        public System.Data.DataTable ThongkeTHH() {
            return base.Channel.ThongkeTHH();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ThongkeTHHAsync() {
            return base.Channel.ThongkeTHHAsync();
        }
        
        public System.Data.DataTable TKDoanhThuMY(string date1) {
            return base.Channel.TKDoanhThuMY(date1);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TKDoanhThuMYAsync(string date1) {
            return base.Channel.TKDoanhThuMYAsync(date1);
        }
        
        public System.Data.DataTable TKDoanhThuY(string date2) {
            return base.Channel.TKDoanhThuY(date2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TKDoanhThuYAsync(string date2) {
            return base.Channel.TKDoanhThuYAsync(date2);
        }
        
        public System.Data.DataTable TKDoanhThu() {
            return base.Channel.TKDoanhThu();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TKDoanhThuAsync() {
            return base.Channel.TKDoanhThuAsync();
        }
        
        public System.Data.DataTable TimKiemKH(string cmnd) {
            return base.Channel.TimKiemKH(cmnd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TimKiemKHAsync(string cmnd) {
            return base.Channel.TimKiemKHAsync(cmnd);
        }
        
        public int ThemKH(string ten, string SDT, string cmtnd) {
            return base.Channel.ThemKH(ten, SDT, cmtnd);
        }
        
        public System.Threading.Tasks.Task<int> ThemKHAsync(string ten, string SDT, string cmtnd) {
            return base.Channel.ThemKHAsync(ten, SDT, cmtnd);
        }
        
        public System.Data.DataTable TimKiemThuoc_Ban(string cmnd) {
            return base.Channel.TimKiemThuoc_Ban(cmnd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuoc_BanAsync(string cmnd) {
            return base.Channel.TimKiemThuoc_BanAsync(cmnd);
        }
        
        public System.Data.DataTable ThemPhieuXuat(string date, string makh, string manv, string tong) {
            return base.Channel.ThemPhieuXuat(date, makh, manv, tong);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ThemPhieuXuatAsync(string date, string makh, string manv, string tong) {
            return base.Channel.ThemPhieuXuatAsync(date, makh, manv, tong);
        }
        
        public System.Data.DataTable ThemPhieuXuat1(string date, string makh, string manv, string tong) {
            return base.Channel.ThemPhieuXuat1(date, makh, manv, tong);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ThemPhieuXuat1Async(string date, string makh, string manv, string tong) {
            return base.Channel.ThemPhieuXuat1Async(date, makh, manv, tong);
        }
        
        public System.Data.DataTable LayMaPX(string date, string makh, string manv, string tong) {
            return base.Channel.LayMaPX(date, makh, manv, tong);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LayMaPXAsync(string date, string makh, string manv, string tong) {
            return base.Channel.LayMaPXAsync(date, makh, manv, tong);
        }
        
        public int ThemDonThuoc(string maPX, string maT, string sl, string gia) {
            return base.Channel.ThemDonThuoc(maPX, maT, sl, gia);
        }
        
        public System.Threading.Tasks.Task<int> ThemDonThuocAsync(string maPX, string maT, string sl, string gia) {
            return base.Channel.ThemDonThuocAsync(maPX, maT, sl, gia);
        }
        
        public System.Data.DataTable LayThuocDatHang() {
            return base.Channel.LayThuocDatHang();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LayThuocDatHangAsync() {
            return base.Channel.LayThuocDatHangAsync();
        }
        
        public System.Data.DataTable LayThuocDaDatHang(string id) {
            return base.Channel.LayThuocDaDatHang(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LayThuocDaDatHangAsync(string id) {
            return base.Channel.LayThuocDaDatHangAsync(id);
        }
        
        public System.Data.DataTable LayThuocDatHangChiTiet(string id) {
            return base.Channel.LayThuocDatHangChiTiet(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LayThuocDatHangChiTietAsync(string id) {
            return base.Channel.LayThuocDatHangChiTietAsync(id);
        }
        
        public System.Data.DataTable LayThuocDonThuoc() {
            return base.Channel.LayThuocDonThuoc();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LayThuocDonThuocAsync() {
            return base.Channel.LayThuocDonThuocAsync();
        }
        
        public System.Data.DataTable TimKiemThuocDonThuoc(string str) {
            return base.Channel.TimKiemThuocDonThuoc(str);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuocDonThuocAsync(string str) {
            return base.Channel.TimKiemThuocDonThuocAsync(str);
        }
        
        public System.Data.DataTable TimKiemChiTietDonThuoc(string str) {
            return base.Channel.TimKiemChiTietDonThuoc(str);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TimKiemChiTietDonThuocAsync(string str) {
            return base.Channel.TimKiemChiTietDonThuocAsync(str);
        }
        
        public void XoaDon(string id) {
            base.Channel.XoaDon(id);
        }
        
        public System.Threading.Tasks.Task XoaDonAsync(string id) {
            return base.Channel.XoaDonAsync(id);
        }
        
        public QLBanThuoc.QL_SR.THUOC[] LayDS(string str) {
            return base.Channel.LayDS(str);
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> LayDSAsync(string str) {
            return base.Channel.LayDSAsync(str);
        }
        
        public QLBanThuoc.QL_SR.KHACHHANG[] Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.KHACHHANG[]> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public QLBanThuoc.QL_SR.THUOC[] TimKiem_W(string str) {
            return base.Channel.TimKiem_W(str);
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> TimKiem_WAsync(string str) {
            return base.Channel.TimKiem_WAsync(str);
        }
        
        public int Register(string email, string password, string name, string makh) {
            return base.Channel.Register(email, password, name, makh);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(string email, string password, string name, string makh) {
            return base.Channel.RegisterAsync(email, password, name, makh);
        }
        
        public QLBanThuoc.QL_SR.THUOC[] LayTenLoaiThuoc(string str) {
            return base.Channel.LayTenLoaiThuoc(str);
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> LayTenLoaiThuocAsync(string str) {
            return base.Channel.LayTenLoaiThuocAsync(str);
        }
        
        public QLBanThuoc.QL_SR.THUOC[] ChiTietSP(string str) {
            return base.Channel.ChiTietSP(str);
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> ChiTietSPAsync(string str) {
            return base.Channel.ChiTietSPAsync(str);
        }
        
        public QLBanThuoc.QL_SR.LOAITHUOC[] LayDSLoaiThuoc(string str) {
            return base.Channel.LayDSLoaiThuoc(str);
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.LOAITHUOC[]> LayDSLoaiThuocAsync(string str) {
            return base.Channel.LayDSLoaiThuocAsync(str);
        }
        
        public QLBanThuoc.QL_SR.KHACHHANG[] ThongTinKH(string str) {
            return base.Channel.ThongTinKH(str);
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.KHACHHANG[]> ThongTinKHAsync(string str) {
            return base.Channel.ThongTinKHAsync(str);
        }
        
        public QLBanThuoc.QL_SR.GIOHANG[] ThongTinGH(string maKH, string maT) {
            return base.Channel.ThongTinGH(maKH, maT);
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.GIOHANG[]> ThongTinGHAsync(string maKH, string maT) {
            return base.Channel.ThongTinGHAsync(maKH, maT);
        }
        
        public QLBanThuoc.QL_SR.KHUYENMAI[] TienKM(string coupon) {
            return base.Channel.TienKM(coupon);
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.KHUYENMAI[]> TienKMAsync(string coupon) {
            return base.Channel.TienKMAsync(coupon);
        }
        
        public int ThemSP(string maT, string maKH, int sl) {
            return base.Channel.ThemSP(maT, maKH, sl);
        }
        
        public System.Threading.Tasks.Task<int> ThemSPAsync(string maT, string maKH, int sl) {
            return base.Channel.ThemSPAsync(maT, maKH, sl);
        }
        
        public int XoaSP(string maKH, string maT) {
            return base.Channel.XoaSP(maKH, maT);
        }
        
        public System.Threading.Tasks.Task<int> XoaSPAsync(string maKH, string maT) {
            return base.Channel.XoaSPAsync(maKH, maT);
        }
        
        public int ThemHoaDon(string ho, string ten, string diachiduong, string sonha, string email, string sdt, string ghichu, string makhuyenmai, string giaohang) {
            return base.Channel.ThemHoaDon(ho, ten, diachiduong, sonha, email, sdt, ghichu, makhuyenmai, giaohang);
        }
        
        public System.Threading.Tasks.Task<int> ThemHoaDonAsync(string ho, string ten, string diachiduong, string sonha, string email, string sdt, string ghichu, string makhuyenmai, string giaohang) {
            return base.Channel.ThemHoaDonAsync(ho, ten, diachiduong, sonha, email, sdt, ghichu, makhuyenmai, giaohang);
        }
        
        public QLBanThuoc.QL_SR.HOADON[] LayMaHD(string ho, string ten, string diachiduong, string sonha, string email, string sdt) {
            return base.Channel.LayMaHD(ho, ten, diachiduong, sonha, email, sdt);
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.HOADON[]> LayMaHDAsync(string ho, string ten, string diachiduong, string sonha, string email, string sdt) {
            return base.Channel.LayMaHDAsync(ho, ten, diachiduong, sonha, email, sdt);
        }
        
        public int ThemCCHoaDon(int maHD, string maT, int dongia, int sl) {
            return base.Channel.ThemCCHoaDon(maHD, maT, dongia, sl);
        }
        
        public System.Threading.Tasks.Task<int> ThemCCHoaDonAsync(int maHD, string maT, int dongia, int sl) {
            return base.Channel.ThemCCHoaDonAsync(maHD, maT, dongia, sl);
        }
        
        public QLBanThuoc.QL_SR.THUOC[] SanPhamBanChay() {
            return base.Channel.SanPhamBanChay();
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> SanPhamBanChayAsync() {
            return base.Channel.SanPhamBanChayAsync();
        }
        
        public QLBanThuoc.QL_SR.THUOC[] SanPhamMoi() {
            return base.Channel.SanPhamMoi();
        }
        
        public System.Threading.Tasks.Task<QLBanThuoc.QL_SR.THUOC[]> SanPhamMoiAsync() {
            return base.Channel.SanPhamMoiAsync();
        }
    }
}
