//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanThuoc.QL_SR {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QL_SR.QLBanThuocServiceSoap")]
    public interface QLBanThuocServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemMoiNCC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ThemMoiNCC(string mancc, string tenncc, string nguoidd, string sdt, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemMoiNCC", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ThemMoiNCCAsync(string mancc, string tenncc, string nguoidd, string sdt, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuaNhaCungCap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SuaNhaCungCap(string mancc, string tenncc, string nguoidd, string sdt, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuaNhaCungCap", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SuaNhaCungCapAsync(string mancc, string tenncc, string nguoidd, string sdt, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaNhaCungCap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int XoaNhaCungCap(string mancc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaNhaCungCap", ReplyAction="*")]
        System.Threading.Tasks.Task<int> XoaNhaCungCapAsync(string mancc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemNCC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiemNCC(string thongtin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemNCC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TimKiemNCCAsync(string thongtin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getID(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getIDAsync(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ma_user", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ma_user();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ma_user", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ma_userAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiemThuoc(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuocAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuocSua", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiemThuocSua(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiemThuocSua", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuocSuaAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LuuThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int LuuThuoc(string mathuoc, string malo, string ten, string tp, string cd, string nsx, string hsd, string slt, string dt, string dongia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LuuThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<int> LuuThuocAsync(string mathuoc, string malo, string ten, string tp, string cd, string nsx, string hsd, string slt, string dt, string dongia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaThuoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int XoaThuoc(string maThuoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaThuoc", ReplyAction="*")]
        System.Threading.Tasks.Task<int> XoaThuocAsync(string maThuoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThuocTheoTen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DanhSachThuocTheoTen(string TenThuoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThuocTheoTen", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DanhSachThuocTheoTenAsync(string TenThuoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QLBanThuocServiceSoapChannel : QLBanThuoc.QL_SR.QLBanThuocServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QLBanThuocServiceSoapClient : System.ServiceModel.ClientBase<QLBanThuoc.QL_SR.QLBanThuocServiceSoap>, QLBanThuoc.QL_SR.QLBanThuocServiceSoap {
        
        public QLBanThuocServiceSoapClient() {
        }
        
        public QLBanThuocServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QLBanThuocServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLBanThuocServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLBanThuocServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ThemMoiNCC(string mancc, string tenncc, string nguoidd, string sdt, string diachi) {
            return base.Channel.ThemMoiNCC(mancc, tenncc, nguoidd, sdt, diachi);
        }
        
        public System.Threading.Tasks.Task<int> ThemMoiNCCAsync(string mancc, string tenncc, string nguoidd, string sdt, string diachi) {
            return base.Channel.ThemMoiNCCAsync(mancc, tenncc, nguoidd, sdt, diachi);
        }
        
        public int SuaNhaCungCap(string mancc, string tenncc, string nguoidd, string sdt, string diachi) {
            return base.Channel.SuaNhaCungCap(mancc, tenncc, nguoidd, sdt, diachi);
        }
        
        public System.Threading.Tasks.Task<int> SuaNhaCungCapAsync(string mancc, string tenncc, string nguoidd, string sdt, string diachi) {
            return base.Channel.SuaNhaCungCapAsync(mancc, tenncc, nguoidd, sdt, diachi);
        }
        
        public int XoaNhaCungCap(string mancc) {
            return base.Channel.XoaNhaCungCap(mancc);
        }
        
        public System.Threading.Tasks.Task<int> XoaNhaCungCapAsync(string mancc) {
            return base.Channel.XoaNhaCungCapAsync(mancc);
        }
        
        public System.Data.DataTable TimKiemNCC(string thongtin) {
            return base.Channel.TimKiemNCC(thongtin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TimKiemNCCAsync(string thongtin) {
            return base.Channel.TimKiemNCCAsync(thongtin);
        }
        
        public string getID(string username, string pass) {
            return base.Channel.getID(username, pass);
        }
        
        public System.Threading.Tasks.Task<string> getIDAsync(string username, string pass) {
            return base.Channel.getIDAsync(username, pass);
        }
        
        public string ma_user() {
            return base.Channel.ma_user();
        }
        
        public System.Threading.Tasks.Task<string> ma_userAsync() {
            return base.Channel.ma_userAsync();
        }
        
        public System.Data.DataTable TimKiemThuoc(string str) {
            return base.Channel.TimKiemThuoc(str);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuocAsync(string str) {
            return base.Channel.TimKiemThuocAsync(str);
        }
        
        public System.Data.DataTable TimKiemThuocSua(string str) {
            return base.Channel.TimKiemThuocSua(str);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TimKiemThuocSuaAsync(string str) {
            return base.Channel.TimKiemThuocSuaAsync(str);
        }
        
        public int LuuThuoc(string mathuoc, string malo, string ten, string tp, string cd, string nsx, string hsd, string slt, string dt, string dongia) {
            return base.Channel.LuuThuoc(mathuoc, malo, ten, tp, cd, nsx, hsd, slt, dt, dongia);
        }
        
        public System.Threading.Tasks.Task<int> LuuThuocAsync(string mathuoc, string malo, string ten, string tp, string cd, string nsx, string hsd, string slt, string dt, string dongia) {
            return base.Channel.LuuThuocAsync(mathuoc, malo, ten, tp, cd, nsx, hsd, slt, dt, dongia);
        }
        
        public int XoaThuoc(string maThuoc) {
            return base.Channel.XoaThuoc(maThuoc);
        }
        
        public System.Threading.Tasks.Task<int> XoaThuocAsync(string maThuoc) {
            return base.Channel.XoaThuocAsync(maThuoc);
        }
        
        public System.Data.DataTable DanhSachThuocTheoTen(string TenThuoc) {
            return base.Channel.DanhSachThuocTheoTen(TenThuoc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DanhSachThuocTheoTenAsync(string TenThuoc) {
            return base.Channel.DanhSachThuocTheoTenAsync(TenThuoc);
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string HelloName(string name) {
            return base.Channel.HelloName(name);
        }
        
        public System.Threading.Tasks.Task<string> HelloNameAsync(string name) {
            return base.Channel.HelloNameAsync(name);
        }
    }
}
