//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanThuoc.QLBanThuocServiceRf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QLBanThuocServiceRf.IQLBanThuocService")]
    public interface IQLBanThuocService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLBanThuocService/AddNumbers", ReplyAction="http://tempuri.org/IQLBanThuocService/AddNumbersResponse")]
        double AddNumbers(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLBanThuocService/AddNumbers", ReplyAction="http://tempuri.org/IQLBanThuocService/AddNumbersResponse")]
        System.Threading.Tasks.Task<double> AddNumbersAsync(double x, double y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQLBanThuocServiceChannel : QLBanThuoc.QLBanThuocServiceRf.IQLBanThuocService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QLBanThuocServiceClient : System.ServiceModel.ClientBase<QLBanThuoc.QLBanThuocServiceRf.IQLBanThuocService>, QLBanThuoc.QLBanThuocServiceRf.IQLBanThuocService {
        
        public QLBanThuocServiceClient() {
        }
        
        public QLBanThuocServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QLBanThuocServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLBanThuocServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLBanThuocServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double AddNumbers(double x, double y) {
            return base.Channel.AddNumbers(x, y);
        }
        
        public System.Threading.Tasks.Task<double> AddNumbersAsync(double x, double y) {
            return base.Channel.AddNumbersAsync(x, y);
        }
    }
}
